spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student  # Replace 'mydatabase' with your actual database name
    username: yourUsername
    password: yourPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
